# Souls Plugin Configuration

# Starting number of souls for new players
starting-souls: 3

# Soul power thresholds
powers:
  speed: 5        # Speed effect at 5+ souls
  jump: 8         # Jump boost at 8+ souls
  water-breathing: 12  # Water breathing at 12+ souls
  night-vision: 15     # Night vision at 15+ souls
  strength: 20    # Strength effect at 20+ souls
  regeneration: 25     # Regeneration at 25+ souls
  flight: 30      # Flight ability at 30+ souls

# Messages
messages:
  soul-lost: "You lost a soul! Souls remaining: %souls%"
  became-ghost: "You have lost all your souls! You are now a ghost."
  soul-gained: "You gained a soul! Total: %souls%"
  soul-picked-up: "You picked up a soul! Total: %souls%"
  ghost-message: "You are a ghost! Ask someone to revive you with /revive"
  revived: "%reviver% revived you! You have 1 soul."
  revive-success: "You revived %ghost%! You now have %souls% souls."